run:
  timeout: 10m
  # Removed "skip-files" since it's not allowed in this version

output:
  # Removed the "format" key since it's not allowed; default format will be used

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    # Removed deprecated "ignore" key
  govet: {}  # Removed "check-shadowing" as it's no longer supported
  gofmt:
    simplify: true
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/crossplane)
      - prefix(github.com/crossplane-contrib)
      - blank
      - dot
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    tab-width: 1
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - performance
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  nolintlint:
    require-explanation: true
    require-specific: true
  # Removed the "maligned" section as it's no longer allowed

linters:
  enable:
    - megacheck
    - govet
    - gocyclo
    - gocritic
    - goconst
    - gci
    - gofmt
    - prealloc
    - unconvert
    - misspell
    - nakedret
    - nolintlint
  disable:
    - revive
    - deadcode
    - varcheck
    - scopelint
    - structcheck
    - interfacer
  presets:
    - bugs
    - unused
  fast: false

issues:
  exclude-rules:
    - path: _test(ing)?\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
        - unparam
    - path: _test\.go
      text: "(unnamedResult|exitAfterDefer)"
      linters:
        - gocritic
    - text: "(hugeParam|rangeValCopy):"
      linters:
        - gocritic
    - text: "SA3000:"
      linters:
        - staticcheck
    - text: "k8s.io/api/core/v1"
      linters:
        - goimports
    - text: "G101:"
      linters:
        - gosec
        - gas
    - text: "G104:"
      linters:
        - gosec
        - gas
    - path: k8s.io/
      linters:
        - musttag
  exclude-use-default: false
  new: false
  # Replace max-per-linter with max-issues-per-linter:
  max-issues-per-linter: 0
  max-same-issues: 0

